// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: heartbeat.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializeheartbeat")
public inline fun heartbeat(block: touchpad.v1.HeartbeatKt.Dsl.() -> kotlin.Unit): touchpad.v1.HeartbeatOuterClass.Heartbeat =
  touchpad.v1.HeartbeatKt.Dsl._create(touchpad.v1.HeartbeatOuterClass.Heartbeat.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `touchpad.v1.Heartbeat`
 */
public object HeartbeatKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.HeartbeatOuterClass.Heartbeat.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.HeartbeatOuterClass.Heartbeat.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.HeartbeatOuterClass.Heartbeat = _builder.build()

    /**
     * `.touchpad.v1.HeartbeatDir dir = 1;`
     */
    public var dir: touchpad.v1.HeartbeatOuterClass.HeartbeatDir
      @kotlin.jvm.JvmName("getDir")
        get() = _builder.dir
      @kotlin.jvm.JvmName("setDir")
        set(value) {
        _builder.dir = value
      }
    public var dirValue: kotlin.Int
      @kotlin.jvm.JvmName("getDirValue")
        get() = _builder.dirValue
      @kotlin.jvm.JvmName("setDirValue")
        set(value) {
        _builder.dirValue = value
      }
    /**
     * `.touchpad.v1.HeartbeatDir dir = 1;`
     */
    public fun clearDir() {
      _builder.clearDir()
    }

    /**
     * ```
     * 发送方本地毫秒时间戳（用于 RTT 计算）
     * ```
     *
     * `fixed32 send_ts = 2;`
     */
    public var sendTs: kotlin.Int
      @kotlin.jvm.JvmName("getSendTs")
        get() = _builder.sendTs
      @kotlin.jvm.JvmName("setSendTs")
        set(value) {
        _builder.sendTs = value
      }
    /**
     * ```
     * 发送方本地毫秒时间戳（用于 RTT 计算）
     * ```
     *
     * `fixed32 send_ts = 2;`
     */
    public fun clearSendTs() {
      _builder.clearSendTs()
    }

    /**
     * ```
     * 自增序列号，丢包/乱序统计
     * ```
     *
     * `uint32 seq = 3;`
     */
    public var seq: kotlin.Int
      @kotlin.jvm.JvmName("getSeq")
        get() = _builder.seq
      @kotlin.jvm.JvmName("setSeq")
        set(value) {
        _builder.seq = value
      }
    /**
     * ```
     * 自增序列号，丢包/乱序统计
     * ```
     *
     * `uint32 seq = 3;`
     */
    public fun clearSeq() {
      _builder.clearSeq()
    }

    /**
     * ```
     * 可选 0-8 byte，透传（如客户端 ID 前缀）
     * ```
     *
     * `bytes cookie = 4;`
     */
    public var cookie: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getCookie")
        get() = _builder.cookie
      @kotlin.jvm.JvmName("setCookie")
        set(value) {
        _builder.cookie = value
      }
    /**
     * ```
     * 可选 0-8 byte，透传（如客户端 ID 前缀）
     * ```
     *
     * `bytes cookie = 4;`
     */
    public fun clearCookie() {
      _builder.clearCookie()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.HeartbeatOuterClass.Heartbeat.copy(block: `touchpad.v1`.HeartbeatKt.Dsl.() -> kotlin.Unit): touchpad.v1.HeartbeatOuterClass.Heartbeat =
  `touchpad.v1`.HeartbeatKt.Dsl._create(this.toBuilder()).apply { block() }._build()

