// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: handshake.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializehello")
public inline fun hello(block: touchpad.v1.HelloKt.Dsl.() -> kotlin.Unit): touchpad.v1.Handshake.Hello =
  touchpad.v1.HelloKt.Dsl._create(touchpad.v1.Handshake.Hello.newBuilder()).apply { block() }._build()
/**
 * ```
 * 手机端发出握手请求
 * ```
 *
 * Protobuf type `touchpad.v1.Hello`
 */
public object HelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.Handshake.Hello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.Handshake.Hello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.Handshake.Hello = _builder.build()

    /**
     * `string os = 1;`
     */
    public var os: kotlin.String
      @kotlin.jvm.JvmName("getOs")
        get() = _builder.os
      @kotlin.jvm.JvmName("setOs")
        set(value) {
        _builder.os = value
      }
    /**
     * `string os = 1;`
     */
    public fun clearOs() {
      _builder.clearOs()
    }

    /**
     * `uint32 version = 2;`
     */
    public var version: kotlin.Int
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `uint32 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string name = 3;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 3;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string token = 4;`
     */
    public var token: kotlin.String
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * `string token = 4;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.Handshake.Hello.copy(block: `touchpad.v1`.HelloKt.Dsl.() -> kotlin.Unit): touchpad.v1.Handshake.Hello =
  `touchpad.v1`.HelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

