// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: touch_packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializepointer")
public inline fun pointer(block: touchpad.v1.PointerKt.Dsl.() -> kotlin.Unit): touchpad.v1.TouchPacketOuterClass.Pointer =
  touchpad.v1.PointerKt.Dsl._create(touchpad.v1.TouchPacketOuterClass.Pointer.newBuilder()).apply { block() }._build()
/**
 * ```
 * 单点信息
 * ```
 *
 * Protobuf type `touchpad.v1.Pointer`
 */
public object PointerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.TouchPacketOuterClass.Pointer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.TouchPacketOuterClass.Pointer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.TouchPacketOuterClass.Pointer = _builder.build()

    /**
     * ```
     * Android pointerId / iOS touch.identifier
     * ```
     *
     * `uint32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Android pointerId / iOS touch.identifier
     * ```
     *
     * `uint32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * 绝对坐标 0..32767 （放大避免浮点）
     * ```
     *
     * `uint32 x = 2;`
     */
    public var x: kotlin.Int
      @kotlin.jvm.JvmName("getX")
        get() = _builder.x
      @kotlin.jvm.JvmName("setX")
        set(value) {
        _builder.x = value
      }
    /**
     * ```
     * 绝对坐标 0..32767 （放大避免浮点）
     * ```
     *
     * `uint32 x = 2;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * ```
     * 绝对坐标 0..32767
     * ```
     *
     * `uint32 y = 3;`
     */
    public var y: kotlin.Int
      @kotlin.jvm.JvmName("getY")
        get() = _builder.y
      @kotlin.jvm.JvmName("setY")
        set(value) {
        _builder.y = value
      }
    /**
     * ```
     * 绝对坐标 0..32767
     * ```
     *
     * `uint32 y = 3;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * ```
     * 0..1023，无压感设备填 1023
     * ```
     *
     * `uint32 pressure = 4;`
     */
    public var pressure: kotlin.Int
      @kotlin.jvm.JvmName("getPressure")
        get() = _builder.pressure
      @kotlin.jvm.JvmName("setPressure")
        set(value) {
        _builder.pressure = value
      }
    /**
     * ```
     * 0..1023，无压感设备填 1023
     * ```
     *
     * `uint32 pressure = 4;`
     */
    public fun clearPressure() {
      _builder.clearPressure()
    }

    /**
     * ```
     * 手指、笔、鼠标
     * ```
     *
     * `.touchpad.v1.ToolType tool = 5;`
     */
    public var tool: touchpad.v1.TouchPacketOuterClass.ToolType
      @kotlin.jvm.JvmName("getTool")
        get() = _builder.tool
      @kotlin.jvm.JvmName("setTool")
        set(value) {
        _builder.tool = value
      }
    public var toolValue: kotlin.Int
      @kotlin.jvm.JvmName("getToolValue")
        get() = _builder.toolValue
      @kotlin.jvm.JvmName("setToolValue")
        set(value) {
        _builder.toolValue = value
      }
    /**
     * ```
     * 手指、笔、鼠标
     * ```
     *
     * `.touchpad.v1.ToolType tool = 5;`
     */
    public fun clearTool() {
      _builder.clearTool()
    }

    /**
     * ```
     * 接触面直径，单位 0.1 mm，可选
     * ```
     *
     * `uint32 contact_size = 6;`
     */
    public var contactSize: kotlin.Int
      @kotlin.jvm.JvmName("getContactSize")
        get() = _builder.contactSize
      @kotlin.jvm.JvmName("setContactSize")
        set(value) {
        _builder.contactSize = value
      }
    /**
     * ```
     * 接触面直径，单位 0.1 mm，可选
     * ```
     *
     * `uint32 contact_size = 6;`
     */
    public fun clearContactSize() {
      _builder.clearContactSize()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.TouchPacketOuterClass.Pointer.copy(block: `touchpad.v1`.PointerKt.Dsl.() -> kotlin.Unit): touchpad.v1.TouchPacketOuterClass.Pointer =
  `touchpad.v1`.PointerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

