// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: touch_packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializetouchPacket")
public inline fun touchPacket(block: touchpad.v1.TouchPacketKt.Dsl.() -> kotlin.Unit): touchpad.v1.TouchPacketOuterClass.TouchPacket =
  touchpad.v1.TouchPacketKt.Dsl._create(touchpad.v1.TouchPacketOuterClass.TouchPacket.newBuilder()).apply { block() }._build()
/**
 * ```
 * 主消息：一条网络包只含一个 TouchPacket
 * ```
 *
 * Protobuf type `touchpad.v1.TouchPacket`
 */
public object TouchPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.TouchPacketOuterClass.TouchPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.TouchPacketOuterClass.TouchPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.TouchPacketOuterClass.TouchPacket = _builder.build()

    /**
     * ```
     * ---- 头部（必须存在，8 byte 以内） ----//
     * ```
     *
     * `uint32 ts_ms = 1;`
     */
    public var tsMs: kotlin.Int
      @kotlin.jvm.JvmName("getTsMs")
        get() = _builder.tsMs
      @kotlin.jvm.JvmName("setTsMs")
        set(value) {
        _builder.tsMs = value
      }
    /**
     * ```
     * ---- 头部（必须存在，8 byte 以内） ----//
     * ```
     *
     * `uint32 ts_ms = 1;`
     */
    public fun clearTsMs() {
      _builder.clearTsMs()
    }

    /**
     * ```
     * 自增序列号，方便丢包统计
     * ```
     *
     * `uint32 seq = 2;`
     */
    public var seq: kotlin.Int
      @kotlin.jvm.JvmName("getSeq")
        get() = _builder.seq
      @kotlin.jvm.JvmName("setSeq")
        set(value) {
        _builder.seq = value
      }
    /**
     * ```
     * 自增序列号，方便丢包统计
     * ```
     *
     * `uint32 seq = 2;`
     */
    public fun clearSeq() {
      _builder.clearSeq()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PointersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     */
     public val pointers: com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.pointersList
      )
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     * @param value The pointers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPointers")
    public fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.add(value: touchpad.v1.TouchPacketOuterClass.Pointer) {
      _builder.addPointers(value)
    }
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     * @param value The pointers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPointers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.plusAssign(value: touchpad.v1.TouchPacketOuterClass.Pointer) {
      add(value)
    }
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     * @param values The pointers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPointers")
    public fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.addAll(values: kotlin.collections.Iterable<touchpad.v1.TouchPacketOuterClass.Pointer>) {
      _builder.addAllPointers(values)
    }
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     * @param values The pointers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPointers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.plusAssign(values: kotlin.collections.Iterable<touchpad.v1.TouchPacketOuterClass.Pointer>) {
      addAll(values)
    }
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     * @param index The index to set the value at.
     * @param value The pointers to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPointers")
    public operator fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.set(index: kotlin.Int, value: touchpad.v1.TouchPacketOuterClass.Pointer) {
      _builder.setPointers(index, value)
    }
    /**
     * ```
     * ---- 业务数据 ----//
     * ```
     *
     * `repeated .touchpad.v1.Pointer pointers = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearPointers")
    public fun com.google.protobuf.kotlin.DslList<touchpad.v1.TouchPacketOuterClass.Pointer, PointersProxy>.clear() {
      _builder.clearPointers()
    }

    /**
     * ```
     * 手势识别结果，若无手势则 NONE
     * ```
     *
     * `.touchpad.v1.GestureType gesture = 4;`
     */
    public var gesture: touchpad.v1.TouchPacketOuterClass.GestureType
      @kotlin.jvm.JvmName("getGesture")
        get() = _builder.gesture
      @kotlin.jvm.JvmName("setGesture")
        set(value) {
        _builder.gesture = value
      }
    public var gestureValue: kotlin.Int
      @kotlin.jvm.JvmName("getGestureValue")
        get() = _builder.gestureValue
      @kotlin.jvm.JvmName("setGestureValue")
        set(value) {
        _builder.gestureValue = value
      }
    /**
     * ```
     * 手势识别结果，若无手势则 NONE
     * ```
     *
     * `.touchpad.v1.GestureType gesture = 4;`
     */
    public fun clearGesture() {
      _builder.clearGesture()
    }

    /**
     * ```
     * 双指滚动增量，无滚动则 0
     * ```
     *
     * `sint32 scroll_dx = 5;`
     */
    public var scrollDx: kotlin.Int
      @kotlin.jvm.JvmName("getScrollDx")
        get() = _builder.scrollDx
      @kotlin.jvm.JvmName("setScrollDx")
        set(value) {
        _builder.scrollDx = value
      }
    /**
     * ```
     * 双指滚动增量，无滚动则 0
     * ```
     *
     * `sint32 scroll_dx = 5;`
     */
    public fun clearScrollDx() {
      _builder.clearScrollDx()
    }

    /**
     * ```
     * 双指滚动增量，无滚动则 0
     * ```
     *
     * `sint32 scroll_dy = 6;`
     */
    public var scrollDy: kotlin.Int
      @kotlin.jvm.JvmName("getScrollDy")
        get() = _builder.scrollDy
      @kotlin.jvm.JvmName("setScrollDy")
        set(value) {
        _builder.scrollDy = value
      }
    /**
     * ```
     * 双指滚动增量，无滚动则 0
     * ```
     *
     * `sint32 scroll_dy = 6;`
     */
    public fun clearScrollDy() {
      _builder.clearScrollDy()
    }

    /**
     * ```
     * ---- 扩展预留 ----//
     * ```
     *
     * `bytes reserved = 15;`
     */
    public var reserved: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getReserved")
        get() = _builder.reserved
      @kotlin.jvm.JvmName("setReserved")
        set(value) {
        _builder.reserved = value
      }
    /**
     * ```
     * ---- 扩展预留 ----//
     * ```
     *
     * `bytes reserved = 15;`
     */
    public fun clearReserved() {
      _builder.clearReserved()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.TouchPacketOuterClass.TouchPacket.copy(block: `touchpad.v1`.TouchPacketKt.Dsl.() -> kotlin.Unit): touchpad.v1.TouchPacketOuterClass.TouchPacket =
  `touchpad.v1`.TouchPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

