// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: handshake.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializewelcome")
public inline fun welcome(block: touchpad.v1.WelcomeKt.Dsl.() -> kotlin.Unit): touchpad.v1.Handshake.Welcome =
  touchpad.v1.WelcomeKt.Dsl._create(touchpad.v1.Handshake.Welcome.newBuilder()).apply { block() }._build()
/**
 * ```
 * 服务器端响应握手请求
 * ```
 *
 * Protobuf type `touchpad.v1.Welcome`
 */
public object WelcomeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.Handshake.Welcome.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.Handshake.Welcome.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.Handshake.Welcome = _builder.build()

    /**
     * `uint32 screen_w = 1;`
     */
    public var screenW: kotlin.Int
      @kotlin.jvm.JvmName("getScreenW")
        get() = _builder.screenW
      @kotlin.jvm.JvmName("setScreenW")
        set(value) {
        _builder.screenW = value
      }
    /**
     * `uint32 screen_w = 1;`
     */
    public fun clearScreenW() {
      _builder.clearScreenW()
    }

    /**
     * `uint32 screen_h = 2;`
     */
    public var screenH: kotlin.Int
      @kotlin.jvm.JvmName("getScreenH")
        get() = _builder.screenH
      @kotlin.jvm.JvmName("setScreenH")
        set(value) {
        _builder.screenH = value
      }
    /**
     * `uint32 screen_h = 2;`
     */
    public fun clearScreenH() {
      _builder.clearScreenH()
    }

    /**
     * `string token = 3;`
     */
    public var token: kotlin.String
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * `string token = 3;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.Handshake.Welcome.copy(block: `touchpad.v1`.WelcomeKt.Dsl.() -> kotlin.Unit): touchpad.v1.Handshake.Welcome =
  `touchpad.v1`.WelcomeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

