// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wrapper.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package touchpad.v1;

@kotlin.jvm.JvmName("-initializewrapper")
public inline fun wrapper(block: touchpad.v1.WrapperKt.Dsl.() -> kotlin.Unit): touchpad.v1.WrapperOuterClass.Wrapper =
  touchpad.v1.WrapperKt.Dsl._create(touchpad.v1.WrapperOuterClass.Wrapper.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `touchpad.v1.Wrapper`
 */
public object WrapperKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: touchpad.v1.WrapperOuterClass.Wrapper.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: touchpad.v1.WrapperOuterClass.Wrapper.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): touchpad.v1.WrapperOuterClass.Wrapper = _builder.build()

    /**
     * `.touchpad.v1.ProtoId proto_id = 1;`
     */
    public var protoId: touchpad.v1.WrapperOuterClass.ProtoId
      @kotlin.jvm.JvmName("getProtoId")
        get() = _builder.protoId
      @kotlin.jvm.JvmName("setProtoId")
        set(value) {
        _builder.protoId = value
      }
    public var protoIdValue: kotlin.Int
      @kotlin.jvm.JvmName("getProtoIdValue")
        get() = _builder.protoIdValue
      @kotlin.jvm.JvmName("setProtoIdValue")
        set(value) {
        _builder.protoIdValue = value
      }
    /**
     * `.touchpad.v1.ProtoId proto_id = 1;`
     */
    public fun clearProtoId() {
      _builder.clearProtoId()
    }

    /**
     * `.google.protobuf.Any payload = 2;`
     */
    public var payload: com.google.protobuf.Any
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * `.google.protobuf.Any payload = 2;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }
    /**
     * `.google.protobuf.Any payload = 2;`
     * @return Whether the payload field is set.
     */
    public fun hasPayload(): kotlin.Boolean {
      return _builder.hasPayload()
    }

    public val WrapperKt.Dsl.payloadOrNull: com.google.protobuf.Any?
      get() = _builder.payloadOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun touchpad.v1.WrapperOuterClass.Wrapper.copy(block: `touchpad.v1`.WrapperKt.Dsl.() -> kotlin.Unit): touchpad.v1.WrapperOuterClass.Wrapper =
  `touchpad.v1`.WrapperKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val touchpad.v1.WrapperOuterClass.WrapperOrBuilder.payloadOrNull: com.google.protobuf.Any?
  get() = if (hasPayload()) getPayload() else null

